import Link from "next/link";
import { signOut } from "@/app/auth/actions";

type ActiveSection = "dashboard" | "catalogue" | "suppliers";
type Props = { active: ActiveSection; name: string; role: string; companyName?: string | null };

const navClass = (selected: boolean) => `flex rounded-lg px-3 py-2.5 text-sm font-medium transition ${selected ? "bg-indigo-500 text-white shadow-sm" : "text-slate-300 hover:bg-slate-800 hover:text-white"}`;
const subNavClass = "block rounded-md px-3 py-1.5 text-xs text-slate-400 transition hover:bg-slate-800 hover:text-white";

export function AppSidebar({ active, name, role, companyName }: Props) {
  return <aside className="flex min-h-full flex-col bg-slate-950 px-4 py-6 text-slate-300"><Link href="/" className="mb-9 flex items-center gap-3 px-2"><span className="grid size-10 place-items-center rounded-xl bg-indigo-500 font-black text-white">S</span><span><b className="block text-sm text-white">{companyName || "Stockwise ERP"}</b><span className="text-xs text-slate-500">Inventory & CRM</span></span></Link><nav className="space-y-6"><section><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">Menu</p><Link href="/" className={navClass(active === "dashboard")}>Dashboard</Link></section><section><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">Catalogue</p><Link href="/catalogue" className={navClass(active === "catalogue")}>Products</Link>{active === "catalogue" && <div className="ml-4 mt-1 space-y-1 border-l border-slate-800 pl-2"><Link href="/catalogue#products" className={subNavClass}>Product list</Link><Link href="/catalogue#add-product" className={subNavClass}>Add product</Link><Link href="/catalogue#catalogue-masters" className={subNavClass}>Categories & brands</Link><Link href="/catalogue#units" className={subNavClass}>Units</Link></div>}<Link href="/suppliers" className={navClass(active === "suppliers")}>Suppliers</Link></section><section><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-500">Operations</p><Link href="/#roadmap" className={navClass(false)}>Inventory</Link><Link href="/#roadmap" className={navClass(false)}>Customers</Link><Link href="/#roadmap" className={navClass(false)}>Sales</Link><Link href="/#roadmap" className={navClass(false)}>Reports</Link></section></nav><div className="mt-auto rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="truncate text-xs font-semibold text-white">{name}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-indigo-300">{role.replaceAll("_", " ")}</p><form action={signOut}><button className="mt-4 text-xs font-semibold text-slate-400 hover:text-white">Sign out</button></form></div></aside>;
}
