import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { AppSidebar } from "@/components/app-sidebar";

export const dynamic = "force-dynamic";

export default async function ProductProfile({ params }: { params: Promise<{ id: string }> }) {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const [{ id }, profile, company] = await Promise.all([params, prisma.profile.findUnique({ where: { id: user.id } }), prisma.companySetting.findFirst()]);
  if (!profile?.isActive) redirect("/");
  const product = await prisma.product.findUnique({ where: { id }, include: { category: true, brand: true, unit: true, taxRate: true, variants: true, laptopSpec: true, priceLevels: { orderBy: { effectiveFrom: "desc" } } } });
  if (!product) notFound();
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://erp-web-application-inventory-crm.vercel.app";
  const qrValue = `${appUrl}/catalogue/${product.id}`;
  const qrImage = `https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(qrValue)}`;
  const fields = [["SKU", product.sku], ["Product type", product.type.replaceAll("_", " ")], ["Tracking", product.trackingMode], ["Category", product.category?.name || "—"], ["Brand", product.brand?.name || "—"], ["Unit", product.unit ? `${product.unit.name} (${product.unit.symbol})` : "—"], ["Tax rate", product.taxRate ? `${product.taxRate.name} (${product.taxRate.rate.toString()}%)` : "—"], ["Status", product.isActive ? "Active" : "Inactive"], ["Cost price", product.costPrice.toString()], ["Retail price", product.sellingPrice.toString()], ["Minimum order", String(product.minimumOrderQuantity)], ["Maximum order", product.maximumOrderQuantity ? String(product.maximumOrderQuantity) : "No limit"]] as const;
  return <div className="min-h-screen bg-slate-50 lg:grid lg:grid-cols-[264px_1fr]"><AppSidebar active="catalogue" name={profile.fullName || user.email || "Account"} role={profile.role} companyName={company?.name}/><main className="p-5 sm:p-8 lg:p-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><Link href="/catalogue" className="text-sm font-semibold text-indigo-600">← Back to catalogue</Link><p className="mt-5 text-sm font-bold text-indigo-600">PRODUCT PROFILE</p><h1 className="mt-1 text-3xl font-bold text-slate-950">{product.name}</h1><p className="mt-2 text-sm text-slate-500">{product.description || "No product description."}</p></div><Link href={`/catalogue?edit=${product.id}`} className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">Edit product</Link></div><section className="mt-8 grid gap-6 xl:grid-cols-[1fr_300px]"><article className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Product information</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-800">{value}</dd></div>)}</dl>{product.laptopSpec && <div className="mt-7 border-t pt-6"><h2 className="text-lg font-bold">Laptop attributes</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(product.laptopSpec).filter(([key, value]) => key !== "productId" && value).map(([key, value]) => <div key={key}><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{key.replace(/[A-Z]/g, (letter) => ` ${letter}`).trim()}</p><p className="mt-1 text-sm font-semibold">{String(value)}</p></div>)}</div></div>}<div className="mt-7 border-t pt-6"><h2 className="text-lg font-bold">Variants and price levels</h2><p className="mt-2 text-sm text-slate-600">Variants: {product.variants.map((variant) => variant.sku).join(", ")}</p><div className="mt-3 flex flex-wrap gap-2">{product.priceLevels.map((price) => <span key={price.id} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{price.level}: {price.amount.toString()}</span>)}</div></div></article><aside className="rounded-2xl border bg-white p-6 text-center shadow-sm"><h2 className="text-lg font-bold text-slate-950">Product QR code</h2><img src={qrImage} alt={`QR code for ${product.name}`} width="220" height="220" className="mx-auto mt-5 rounded-xl border p-2"/><p className="mt-4 text-xs text-slate-500">Scan this code to open this product profile.</p><p className="mt-3 break-all rounded-lg bg-slate-50 p-2 font-mono text-[10px] text-slate-500">{product.qrToken}</p></aside></section></main></div>;
}
