import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupplier } from "@/app/v2-actions";
import { V2Nav } from "@/components/v2-nav";

export const dynamic = "force-dynamic";
const field = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-indigo-500";

export default async function SuppliersPage({ searchParams }: { searchParams: Promise<{ q?: string; created?: string }> }) {
  const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const profile = await prisma.profile.findUnique({ where: { id: user.id } }); if (!profile?.isActive) redirect("/");
  const params = await searchParams; const q = params.q?.trim() || "";
  const [suppliers, brands] = await Promise.all([
    prisma.supplier.findMany({ where: q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { taxNumber: { contains: q, mode: "insensitive" } }, { phone: { contains: q, mode: "insensitive" } }] } : undefined, include: { contacts: true, brands: { include: { brand: true } } }, orderBy: { name: "asc" }, take: 100 }),
    prisma.brand.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
  ]);
  const canEdit = ["OWNER", "ADMIN", "MANAGER", "ACCOUNTANT"].includes(profile.role);
  return <main className="mx-auto min-h-screen max-w-7xl bg-slate-50 p-5 sm:p-8"><V2Nav active="suppliers"/><header className="mt-7 flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm font-bold text-indigo-600">V2 · SUPPLIERS</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Supplier register</h1><p className="mt-2 text-sm text-slate-500">Maintain supplier contacts, payment terms, brands and approval status.</p></div><form className="flex gap-2"><input name="q" defaultValue={q} placeholder="Search supplier or tax number" className={field}/><button className="rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white">Search</button></form></header>
    {params.created && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">Supplier created successfully.</p>}
    {canEdit && <form action={createSupplier} className="mt-7 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Add supplier</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><label className="text-sm font-medium">Business name<input required name="name" className={field}/></label><label className="text-sm font-medium">Tax number<input name="taxNumber" className={field}/></label><label className="text-sm font-medium">Status<select name="status" className={field}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label className="text-sm font-medium">Country<input name="country" className={field}/></label><label className="text-sm font-medium">Main email<input name="email" type="email" className={field}/></label><label className="text-sm font-medium">Main phone<input name="phone" className={field}/></label><label className="text-sm font-medium">Payment terms<input name="paymentTerms" placeholder="e.g. Net 30" className={field}/></label><label className="text-sm font-medium">Primary contact<input name="contactName" className={field}/></label><label className="text-sm font-medium">Address<input name="address" className={field}/></label></div><details className="mt-4 rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-semibold">Contact, bank and brands</summary><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><label className="text-sm">Contact person<input name="contactPerson" className={field}/></label><label className="text-sm">Contact email<input name="contactEmail" type="email" className={field}/></label><label className="text-sm">Contact phone<input name="contactPhone" className={field}/></label><label className="text-sm">Bank name<input name="bankName" className={field}/></label><label className="text-sm">Account name<input name="accountName" className={field}/></label><label className="text-sm">Account number<input name="accountNumber" className={field}/></label></div><fieldset className="mt-4"><legend className="text-sm font-medium">Supplied brands</legend><div className="mt-2 flex flex-wrap gap-3">{brands.map(brand => <label key={brand.id} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm"><input type="checkbox" name="brandIds" value={brand.id}/>{brand.name}</label>)}{!brands.length && <span className="text-sm text-slate-500">Add catalogue brands first.</span>}</div></fieldset></details><button className="mt-5 rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-bold text-white">Create supplier</button></form>}
    <section className="mt-7 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Supplier</th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Tax number</th><th className="px-5 py-3">Brands</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{suppliers.map(s => <tr key={s.id} className="border-t"><td className="px-5 py-4 font-semibold text-slate-900">{s.name}<div className="mt-1 text-xs font-normal text-slate-500">{s.country || "No country"}</div></td><td className="px-5 py-4 text-slate-600">{s.contacts[0]?.name || s.contactName || "—"}<div className="mt-1 text-xs">{s.phone || s.contacts[0]?.phone || ""}</div></td><td className="px-5 py-4 text-slate-600">{s.taxNumber || "—"}</td><td className="px-5 py-4 text-slate-600">{s.brands.map(x => x.brand.name).join(", ") || "—"}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${s.status === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{s.status}</span></td></tr>)}{!suppliers.length && <tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">No suppliers found.</td></tr>}</tbody></table></div></section></main>;
}
